name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 拉取仓库
      uses: actions/checkout@v4.2.2

    - name: 安装JDK
      uses: actions/setup-java@v4.7.1
      with:
        java-version: 17
        distribution: zulu

    - name: 构建
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: 上传构建结果
      uses: actions/upload-artifact@v4.6.2
      with:
        name: output
        path: ./app/build/outputs/apk/debug/*
